modLoader="javafml"
loaderVersion="[47,)"
logoFile="tlregen.png"
license="All Rights Reserved"

[[mods]]
	modId="tlregen"
	version="0.2.0"
	displayName="TLReGen"
	credits="burnsqc"
	authors="burnsqc"
	description='''
    TL Registration/Generation.  An API between Forge and your mod that streamlines commonly executed initialization, registration, setup, and resource generation logic.'''

[[dependencies.tlregen]]
    modId="forge" 
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tlregen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"